name: gcs
channels:
  - defaults
#  - conda-forge  # for python-igraph
dependencies:
  - python>=3.6
  - pip
  - numpy
  - scipy
  - matplotlib
#  - python-igraph
  - blist
  - sortedcontainers
#  - pip:
#      - python-igraph